# -*- coding: utf-8 -*-
"""list_in_built_fun.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12wh7PY2A9YVt-UTXe82WYblyfs7cgjny

#**clear()** --clear function in list to remove all the *element*
"""

a=["s","fd",1,234,"sangeetha",9.0]

print(a)

# remove the all element in the list
a.clear()

print(a) # empty list

"""# copy function to copy the given list"""

a=[1,23]

p=a.copy()

print(p)

"""# **count()--** the number of elements with the specified value"""

a=[1,23,4,4,5,6,7,"sangeeta"]
p=a.count(4)
print(p)

p=a.count(1)
print(p)

#extend Add the elements of a list (or any iterable), to the end of the current list

a=[1,2,3]
b=[1,2,3,5,6]
a.extend(b)
print(a)

set(a)

"""# index()	Returns the index of the first element with the specified value"""

a=[1,2,3,4,5,6,7,8]

print(a[0])
print(a[-1])

"""# insert()"""

a=[1,2,3,4,5]

a.insert(4,9)
print(a)

a.insert(0,10)
print(a)

"""#pop()"""

a=[1,2,3,4,5,6]
a.pop(1) # delete index posstion

print(a)

"""# Remove()"""

a=[1,2,3,4,4] # remove at the specific value

a.remove(4)

print(a)

"""# reverse()"""

a=[1,2,3,4,5,6,7,8]

a.reverse()

print(a)

"""# Sort method"""

a=[2,3,5,6,1,9,5,0,23,32,5,6,1,30]

a.sort()

print(a)