# -*- coding: utf-8 -*-
"""list

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hvcYKrw21ueVfMHNWAt-pOovzD93AqlE
"""

list1=[1,2,3,45,45]
print(list1)

#append function 1. an element at the last posstion
list1.append("orange")
print(list1)

list1.append(9)
print(list1)

a1=[1,2,3,5,6]
b1=[23,34,45,45,65]
a1.append(b1)

print(a1)

b2=(1,2,3,4)
a1.append(b2)
print(a1)

b3={12,23,34,34}
a1.append(b3)

print(a1)